Default:
  seed: 0
  adj_hop: 1

cora:
  big: False
  dataset: cora
  batch: 0
  gpu: 2
  seed: 3
  name_view1: v1_adj
  name_view2: v2_diff
  indice_view1: v1_2
  indice_view2: v2_40
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_lr: 0.01
  cls_weight_decay: 0.0005
  cls_dropout: 0.5
  ve_lr: 0.001
  ve_weight_decay: 0.0
  ve_dropout: 0.2
  mi_lr: 0.01
  mi_weight_decay: 0
  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 0.0001
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  add: False
  dele: False
  ptb_feat: False
  ratio: 0.0
  flag: 1

citeseer:
  big: False
  dataset: citeseer
  batch: 0
  gpu: 2
  seed: 3
  name_view1: v1_adj
  name_view2: v2_diff
  indice_view1: v1_2
  indice_view2: v2_40
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_lr: 0.01
  cls_weight_decay: 0.0005
  cls_dropout: 0.5
  ve_lr: 0.001
  ve_weight_decay: 0.0
  ve_dropout: 0.2
  mi_lr: 0.01
  mi_weight_decay: 0
  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 0.0001
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  add: False
  dele: False
  ptb_feat: False
  ratio: 0.0
  flag: 1

pubmed:
  big: False
  dataset: pubmed
  batch: 0
  gpu: 2
  seed: 3
  name_view1: v1_adj
  name_view2: v2_diff
  indice_view1: v1_2
  indice_view2: v2_10
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_lr: 0.01
  cls_weight_decay: 0.0005
  cls_dropout: 0.5
  ve_lr: 0.001
  ve_weight_decay: 0.0
  ve_dropout: 0.2
  mi_lr: 0.01
  mi_weight_decay: 0
  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 0.0001
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  add: False
  dele: False
  ptb_feat: False
  ratio: 0.0
  flag: 1

cornell:
  big: False
  dataset: cornell
  batch: 0
  gpu: 2
  seed: 3
  name_view1: v1_adj
  name_view2: v2_diff
  indice_view1: v1_2
  indice_view2: v2_40
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_lr: 0.01
  cls_weight_decay: 0.0005
  cls_dropout: 0.5
  ve_lr: 0.001
  ve_weight_decay: 0.0
  ve_dropout: 0.2
  mi_lr: 0.01
  mi_weight_decay: 0
  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 0.0001
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  add: False
  dele: False
  ptb_feat: False
  ratio: 0.0
  flag: 1

actor:
  big: False
  dataset: actor
  batch: 0
  gpu: 2
  seed: 3
  name_view1: v1_adj
  name_view2: v2_diff
  indice_view1: v1_2
  indice_view2: v2_40
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_lr: 0.01
  cls_weight_decay: 0.0005
  cls_dropout: 0.5
  ve_lr: 0.001
  ve_weight_decay: 0.0
  ve_dropout: 0.2
  mi_lr: 0.01
  mi_weight_decay: 0
  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 0.0001
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  add: False
  dele: False
  ptb_feat: False
  ratio: 0.0
  flag: 1

texas:
  big: False
  dataset: texas
  batch: 0
  gpu: 2
  seed: 3
  name_view1: v1_adj
  name_view2: v2_diff
  indice_view1: v1_2
  indice_view2: v2_40
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_lr: 0.01
  cls_weight_decay: 0.0005
  cls_dropout: 0.5
  ve_lr: 0.001
  ve_weight_decay: 0.0
  ve_dropout: 0.2
  mi_lr: 0.01
  mi_weight_decay: 0
  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 0.0001
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  add: False
  dele: False
  ptb_feat: False
  ratio: 0.0
  flag: 1

wisconsin:
  big: False
  dataset: wisconsin
  batch: 0
  gpu: 2
  seed: 3
  name_view1: v1_adj
  name_view2: v2_diff
  indice_view1: v1_2
  indice_view2: v2_40
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_lr: 0.01
  cls_weight_decay: 0.0005
  cls_dropout: 0.5
  ve_lr: 0.001
  ve_weight_decay: 0.0
  ve_dropout: 0.2
  mi_lr: 0.01
  mi_weight_decay: 0
  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 0.0001
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  add: False
  dele: False
  ptb_feat: False
  ratio: 0.0
  flag: 1

chameleon:
  big: False
  dataset: chameleon
  batch: 0
  gpu: 2
  seed: 3
  name_view1: v1_adj
  name_view2: v2_diff
  indice_view1: v1_2
  indice_view2: v2_40
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_lr: 0.01
  cls_weight_decay: 0.0005
  cls_dropout: 0.5
  ve_lr: 0.001
  ve_weight_decay: 0.0
  ve_dropout: 0.2
  mi_lr: 0.01
  mi_weight_decay: 0
  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 0.0001
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  add: False
  dele: False
  ptb_feat: False
  ratio: 0.0
  flag: 1

squirrel:
  big: False
  dataset: squirrel
  batch: 0
  gpu: 2
  seed: 3
  name_view1: v1_adj
  name_view2: v2_diff
  indice_view1: v1_2
  indice_view2: v2_40
  cls_hid_1: 16
  com_lambda_v1: 0.1
  com_lambda_v2: 0.1
  gen_hid: 32
  lam: 0.5
  alpha: 0.1
  mi_hid_1: 128
  cls_lr: 0.01
  cls_weight_decay: 0.0005
  cls_dropout: 0.5
  ve_lr: 0.001
  ve_weight_decay: 0.0
  ve_dropout: 0.2
  mi_lr: 0.01
  mi_weight_decay: 0
  main_epoch: 200
  inner_ne_epoch: 5
  inner_cls_epoch: 5
  inner_mi_epoch: 10
  temp_r: 0.0001
  cls_coe: 0.3
  mi_coe: 0.3
  tau: 0.8
  add: False
  dele: False
  ptb_feat: False
  ratio: 0.0
  flag: 1