Default:
  early_stop: 20
  model: 'GTN'
  weight_decay: 0.001
  num_layers: 1
  is_norm: 1
  identity: 1

acm:
  dataset: 'acm'
  num_layers: 2
  epochs: 100
  lr: 0.005
  num_channels: 2
  hid_dim: 128
  identity: 1

dblp:
  dataset: 'dblp'
  num_layers: 2
  epochs: 100
  lr: 0.005
  num_channels: 2
  hid_dim: 64
  identity: 1

yelp:
  dataset: 'yelp'
  num_layers: 1
  epochs: 100
  lr: 0.005
  num_channels: 2
  hid_dim: 128
  identity: 1