Default:
  dataset: cora
  seed: 0
  nlayers: 2
  hid_dim_cla: 32
  hid_dim_dae: 1024
  mlp_dim: 1433
  k: 30
  ratio: 10
  scale: 15
  num_hop: 10
  alpha: 8
  beta: 1
  num_epochs: 2000
  epochs_pre: 400
  epochs_hom: 100
  lr: 0.001
  weight_decay: 0.0005
  dropout_cla: 0.6
  dropout_adj: 0.25
  sparse: False
  lr_cla: 0.01
  patience: 200
  eval_step: 10

cora:
  dataset: cora

citeseer:
  dataset: citeseer
  nlayers: 2
  hid_dim_cla: 32
  hid_dim_dae: 1024
  mlp_dim: 3703
  k: 30
  ratio: 10
  scale: 10
  num_hop: 1
  alpha: 8
  beta: 1
  num_epochs: 2000
  epochs_pre: 400
  epochs_hom: 100
  lr: 0.001
  weight_decay: 0.0005
  dropout_cla: 0.5
  dropout_adj: 0.2
  sparse: False
  lr_cla: 0.01
  patience: 200
  eval_step: 10

pubmed:
  dataset: pubmed
  nlayers: 2
  hid_dim_cla: 64
  hid_dim_dae: 512
  mlp_dim: 500
  k: 20
  ratio: 5
  scale: 5
  num_hop: 10
  alpha: 5
  beta: 1
  num_epochs: 2000
  epochs_pre: 400
  epochs_hom: 100
  lr: 0.01
  weight_decay: 0.0005
  dropout_cla: 0.4
  dropout_adj: 0.3
  sparse: True
  lr_cla: 0.01
  patience: 200
  eval_step: 10

ogbn-arxiv:
  dataset: ogbn-arxiv
  nlayers: 2
  hid_dim_cla: 256
  hid_dim_dae: 512
  mlp_dim: 128
  k: 20
  ratio: 100
  scale: 3
  num_hop: 3
  alpha: 10
  beta: 1
  num_epochs: 2000
  epochs_pre: 0
  epochs_hom: 300
  lr: 0.001
  weight_decay: 0.
  dropout_cla: 0.4
  dropout_adj: 0.5
  sparse: True
  lr_cla: 0.01
  patience: 200
  eval_step: 10

cornell:
  dataset: cornell
  nlayers: 2
  hid_dim_cla: 128
  hid_dim_dae: 1024
  mlp_dim: 1703
  k: 20
  ratio: 20
  scale: 15
  num_hop: 8
  alpha: 8
  beta: 1
  num_epochs: 2000
  epochs_pre: 200
  epochs_hom: 100
  lr: 0.001
  weight_decay: 0.0005
  dropout_cla: 0.6
  dropout_adj: 0.3
  sparse: False
  lr_cla: 0.01
  patience: 200
  eval_step: 10

texas:
  dataset: texas
  nlayers: 2
  hid_dim_cla: 16
  hid_dim_dae: 1024
  mlp_dim: 1703
  k: 5
  ratio: 10
  scale: 5
  num_hop: 5
  alpha: 1
  beta: 1
  num_epochs: 2000
  epochs_pre: 400
  epochs_hom: 100
  lr: 0.001
  weight_decay: 0.0005
  dropout_cla: 0.6
  dropout_adj: 0.1
  sparse: False
  lr_cla: 0.01
  patience: 200
  eval_step: 10

wisconsin:
  dataset: wisconsin
  nlayers: 2
  hid_dim_cla: 32
  hid_dim_dae: 1024
  mlp_dim: 1703
  k: 3
  ratio: 5
  scale: 8
  num_hop: 3
  alpha: 1
  beta: 1
  num_epochs: 2000
  epochs_pre: 400
  epochs_hom: 100
  lr: 0.001
  weight_decay: 0.0005
  dropout_cla: 0.6
  dropout_adj: 0.25
  sparse: False
  lr_cla: 0.01
  patience: 200
  eval_step: 10

actor:
  dataset: actor
  nlayers: 2
  hid_dim_cla: 32
  hid_dim_dae: 256
  mlp_dim: 932
  k: 30
  ratio: 5
  scale: 10
  num_hop: 3
  alpha: 10
  beta: 1
  num_epochs: 2000
  epochs_pre: 400
  epochs_hom: 100
  lr: 0.005
  weight_decay: 0.0005
  dropout_cla: 0.6
  dropout_adj: 0.2
  sparse: False
  lr_cla: 0.01
  patience: 200
  eval_step: 10
