Default:
  alpha: 0.0005
  beta: 1.5
  cuda: true
  debug: false
  dropout: 0.5
  epochs: 400
  gamma: 1
  hidden: 32
  inner_steps: 2
  lambda_: 0
  lr: 0.01
  lr_adj: 0.01
  outer_steps: 1
  phi: 0
  seed: 42
  symmetric: false
  weight_decay: 0.0005
cora:
  alpha: 0.0005
  beta: 1.5
  cuda: true
  debug: false
  dropout: 0.5
  epochs: 400
  gamma: 1
  hidden: 16
  inner_steps: 2
  lambda_: 0
  lr: 0.01
  lr_adj: 0.01
  outer_steps: 1
  phi: 0
  seed: 42
  symmetric: false
  weight_decay: 0.0005
Pubmed:
  alpha: 0.0005
  beta: 1.5
  cuda: true
  debug: false
  dropout: 0.5
  epochs: 400
  gamma: 1
  hidden: 32
  inner_steps: 2
  lambda_: 0
  lr: 0.01
  lr_adj: 0.01
  outer_steps: 1
  phi: 0
  seed: 42
  symmetric: false
  weight_decay: 0.0005