Default:
  epochs: 200
  epochs_adj: 2000
  lr: 0.001
  lr_adj: 0.01
  w_decay: 0.0005
  w_decay_adj: 0.0
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.25
  dataset: cora
  nlayers: 2
  nlayers_adj: 2
  patience: 10
  ntrials: 1
  k: 20
  half_val_as_train: 0
  ratio: 20
  epoch_d: 5
  lambda_: 0.1
  nr: 5
  knn_metric: cosine
  model: end2end
  i: 6
  non_linearity: elu
  mlp_act: relu
  normalization: sym
  mlp_h: 50
  mlp_epochs: 100
  gen_mode: 0
  sparse: 0
  noise: mask
  loss: mse

Cora-FP:
  dataset: cora
  ntrials: 1
  epochs_adj: 2000
  lr: 0.001
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5

Cora-MLP:
  dataset: cora
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_h: 1433
  mlp_act: relu
  epoch_d: 5

Cora-MLPD:
  dataset: cora
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.05
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 15
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 2
  non_linearity: relu
  mlp_act: relu
  epoch_d: 5


Citeseer-FP:
  dataset: citeseer
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.05
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 1024
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.4
  dropout_adj2: 0.4
  k: 30
  lambda_: 1.0
  nr: 1
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5

Citeseer-MLP:
  dataset: citeseer
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 1024
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_act: relu
  mlp_h: 3703
  epoch_d: 5

Citeseer-MLPD:
  dataset: citeseer
  ntrials: 1
  epochs_adj: 2000
  lr: 0.001
  lr_adj: 0.01
  w_decay: 0.05
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 1024
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 2
  non_linearity: relu
  mlp_act: tanh
  epoch_d: 5

Cora390-FP:
  dataset: cora
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 100.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5
  half_val_as_train: 1

Cora390-MLP:
  dataset: cora
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_h: 1433
  mlp_act: relu
  epoch_d: 5
  half_val_as_train: 1

Cora390-MLPD:
  dataset: cora
  ntrials: 1
  epochs_adj: 2000
  lr: 0.001
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 2
  non_linearity: relu
  mlp_act: relu
  epoch_d: 5
  half_val_as_train: 1

Citeseer370-FP:
  dataset: citeseer
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.05
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 1024
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.5
  k: 30
  lambda_: 1.0
  nr: 1
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5
  half_val_as_train: 1

Citeseer370-MLP:
  dataset: citeseer
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 1024
  dropout1: 0.25
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_act: tanh
  mlp_h: 3703
  epoch_d: 5
  half_val_as_train: 1

Citeseer370-MLPD:
  dataset: citeseer
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.05
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 1024
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 2
  non_linearity: relu
  mlp_act: tanh
  epoch_d: 5
  half_val_as_train: 1

Pubmed-MLP:
  dataset: pubmed
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 128
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.5
  k: 15
  lambda_: 10.0
  nr: 5
  ratio: 20
  model: end2end
  gen_mode: 1
  non_linearity: relu
  mlp_h: 500
  mlp_act: relu
  epoch_d: 5
  sparse: 1

Pubmed-MLPD:
  dataset: pubmed
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 128
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.25
  k: 15
  lambda_: 100.0
  nr: 5
  ratio: 20
  model: end2end
  gen_mode: 2
  non_linearity: relu
  mlp_act: tanh
  epoch_d: 5
  sparse: 1

ogbn-arxiv-MLP:
  dataset: ogbn-arxiv
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0
  nlayers: 2
  nlayers_adj: 2
  hidden: 256
  hidden_adj: 256
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 15
  lambda_: 10.0
  nr: 5
  ratio: 100
  model: end2end
  gen_mode: 1
  non_linearity: relu
  mlp_h: 128
  mlp_act: relu
  epoch_d: 2001
  sparse: 1
  loss: mse
  noise: mask

ogbn-arxiv-MLPD:
  dataset: ogbn-arxiv
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0
  nlayers: 2
  nlayers_adj: 2
  hidden: 256
  hidden_adj: 256
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 15
  lambda_: 10.0
  nr: 5
  ratio: 100
  model: end2end
  gen_mode: 2
  non_linearity: relu
  mlp_act: relu
  epoch_d: 2001
  sparse: 1
  loss: mse
  noise: normal

Pubmed-FP:
  dataset: pubmed
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5

cornell-FP:
  dataset: cornell
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5

cornell-MLP:
  dataset: cornell
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_h: 1433
  mlp_act: relu
  epoch_d: 5

actor-FP:
  dataset: actor
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5

actor-MLP:
  dataset: actor
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_h: 1433
  mlp_act: relu
  epoch_d: 5

texas-FP:
  dataset: texas
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5

texas-MLP:
  dataset: texas
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_h: 1433
  mlp_act: relu
  epoch_d: 5

wisconsin-FP:
  dataset: wisconsin
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5

wisconsin-MLP:
  dataset: wisconsin
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_h: 1433
  mlp_act: relu
  epoch_d: 5

chameleon-FP:
  dataset: chameleon
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5

chameleon-MLP:
  dataset: chameleon
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_h: 1433
  mlp_act: relu
  epoch_d: 5

squirrel-FP:
  dataset: squirrel
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5

squirrel-MLP:
  dataset: squirrel
  ntrials: 1
  epochs_adj: 2000
  lr: 0.01
  lr_adj: 0.001
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.25
  dropout_adj2: 0.5
  k: 20
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 0
  gen_mode: 1
  non_linearity: relu
  mlp_h: 1433
  mlp_act: relu
  epoch_d: 5

ogbn-arxiv-FP:
  dataset: ogbn-arxiv
  ntrials: 1
  epochs_adj: 2000
  lr: 0.001
  lr_adj: 0.01
  w_decay: 0.0005
  nlayers: 2
  nlayers_adj: 2
  hidden: 32
  hidden_adj: 512
  dropout1: 0.5
  dropout2: 0.5
  dropout_adj1: 0.5
  dropout_adj2: 0.25
  k: 30
  lambda_: 10.0
  nr: 5
  ratio: 10
  model: end2end
  sparse: 1
  gen_mode: 0
  non_linearity: elu
  epoch_d: 5