Default:
  seed: 1
  dataset: cora
  lr: 0.01
  lr_cls: 0.001
  num_hidden: 512
  num_hidden_eval: 32
  num_rep_dim: 256
  num_proj_dim: 256
  activation: relu
  base_model: GCNConv
  num_layers: 2
  num_layers_eval: 2
  num_epochs: 4000
  num_epochs_cls: 200
  weight_decay: 0
  weight_decay_cls: 0.0005
  mode: structure_refinement
  sparse: False
  k: 30
  dropout: 0.5
  dropout_eval: 0.5
  dropedge_rate: 0.5
  dropedge_rate_eval: 0.75
  tau: 0.9999
  c: 0
  learner: mlp
  maskfeat_rate_anchor: 0.6
  maskfeat_rate_learner: 0.7
  contrast_batch_size: 0

cora:
  lr: 0.01
  lr_cls: 0.001
  num_hidden: 512
  num_hidden_eval: 32
  num_rep_dim: 256
  num_proj_dim: 256
  activation: relu
  base_model: GCNConv
  num_layers: 2
  num_layers_eval: 2
  num_epochs: 4000
  num_epochs_cls: 200
  weight_decay: 0
  weight_decay_cls: 0.0005
  mode: structure_refinement
  sparse: False
  k: 30
  dropout: 0.5
  dropout_eval: 0.5
  dropedge_rate: 0.5
  dropedge_rate_eval: 0.75
  tau: 0.9999
  c: 0
  learner: full
  maskfeat_rate_anchor: 0.6
  maskfeat_rate_learner: 0.7
  contrast_batch_size: 0
  eval_step: 50

citeseer:
  seed: 1
  dataset: citeseer
  lr: 0.001
  lr_cls: 0.001
  num_hidden: 512
  num_hidden_eval: 32
  num_rep_dim: 256
  num_proj_dim: 256
  activation: tanh
  base_model: GCNConv
  num_layers: 2
  num_layers_eval: 2
  num_epochs: 1000
  num_epochs_cls: 200
  weight_decay: 0
  weight_decay_cls: 0.05
  mode: structure_refinement
  sparse: False
  k: 20
  dropout: 0.5
  dropout_eval: 0.5
  dropedge_rate: 0.25
  dropedge_rate_eval: 0.5
  tau: 0.9999
  c: 0
  learner: att
  maskfeat_rate_anchor: 0.8
  maskfeat_rate_learner: 0.6
  contrast_batch_size: 0

pubmed:
  seed: 1
  dataset: pubmed
  lr: 0.001
  lr_cls: 0.01
  num_hidden: 128
  num_hidden_eval: 32
  num_rep_dim: 64
  num_proj_dim: 64
  activation: relu
  base_model: GCNConv
  num_layers: 2
  num_layers_eval: 2
  num_epochs: 1500
  num_epochs_cls: 200
  weight_decay: 0
  weight_decay_cls: 0.0005
  mode: structure_refinement
  sparse: True
  k: 10
  dropout: 0.5
  dropout_eval: 0.5
  dropedge_rate: 0.5
  dropedge_rate_eval: 0.25
  tau: 0.9999
  c: 50
  learner: mlp
  maskfeat_rate_anchor: 0.4
  maskfeat_rate_learner: 0.4
  contrast_batch_size: 2000